### ISSUE TITLE
Installation with Yarn fails without --ignore-engines option

### ISSUE THREAD

**Issue by jtormey** [ramda/ramda-lens#19]
When installing with yarn on any node version other than 6.1.0, the install fails with:

```
error ramda-lens@0.1.1: The engine "node" is incompatible with this module. Expected version "6.1.0".
error Found incompatible module
```

To install, I need to pass --ignore-engines to yarn. It would be nice if the package.json "engines" field was more permissive, maybe ">= 6.1.0"?

**Comment by scott-christopher** [comment]
The engine constraint has been loosened to `>=6.1.0` in #20 and a new version `0.1.2` has been released to npm.
