### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by jimf** [ramda/ramda-lens#3]
Just leaving this here as a reminder :wink:. Thanks for this. Really enjoyed the immutablejs-with-lenses article!

**Comment by davidchambers** [comment]
Shall I open a pull request to integrate [xyz](https://github.com/davidchambers/xyz)?

**Comment by buzzdecafe** [comment]
:+1: xyz

**Comment by gilligan** [comment]
👍

**Comment by netfishx** [comment]
now?

**Comment by Koleok** [comment]
I don't get why this isn't on npm yet :(

**Comment by scott-christopher** [comment]
I'd ideally like to see #6 solved before this gets published. I'll get the discussion going again over in the other issue.

**Comment by Koleok** [comment]
all is in order

**Comment by buzzdecafe** [comment]
done
